"""addinsurance

Revision ID: 01b04e17e4f1
Revises: d6ae25431695
Create Date: 2025-01-12 12:29:26.288054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b04e17e4f1'
down_revision = 'd6ae25431695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_image', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.drop_column('insurance_image')

    # ### end Alembic commands ###
