"""gearpostchanges

Revision ID: 04ce004aa979
Revises: c22ef89c74c6
Create Date: 2025-03-13 23:49:01.715148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ce004aa979'
down_revision = 'c22ef89c74c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_post', schema=None) as batch_op:
        batch_op.drop_column('delivery_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_fee', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
