"""addedemailverifiedcolumn

Revision ID: 183bfc36aa1f
Revises: 2db35fd43176
Create Date: 2025-01-16 23:58:05.848540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183bfc36aa1f'
down_revision = '2db35fd43176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
