"""class

Revision ID: 197154703805
Revises: 6888a0e710ab
Create Date: 2023-08-28 09:56:28.379230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197154703805'
down_revision = '6888a0e710ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_class', 'business_profile', ['business_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_profile_id')

    # ### end Alembic commands ###
