"""Add job_application_id to messages

Revision ID: 19f8a3238290
Revises: a63773ec222d
Create Date: 2024-12-03 14:33:24.139364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f8a3238290'
down_revision = 'a63773ec222d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_application_id', sa.Integer(), nullable=True))
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('job_app', 'job_application', ['job_application_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('job_application_id')

    # ### end Alembic commands ###
