"""Add location field to Job model

Revision ID: 290640f4d666
Revises: ecfb8cef9635
Create Date: 2024-11-25 17:13:56.705402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290640f4d666'
down_revision = 'ecfb8cef9635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
