"""opo

Revision ID: 2b6360ec8108
Revises: aa90b5c88fef
Create Date: 2024-11-30 20:36:32.328503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6360ec8108'
down_revision = 'aa90b5c88fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('established', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.drop_column('established')

    # ### end Alembic commands ###
