"""verif_ready_column

Revision ID: 2db35fd43176
Revises: a038b6ac89ac
Create Date: 2025-01-15 13:42:52.322901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db35fd43176'
down_revision = 'a038b6ac89ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_ready', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.drop_column('verification_ready')

    # ### end Alembic commands ###
