"""lockedcompany

Revision ID: 3665bce2f2a4
Revises: f05d62398913
Create Date: 2025-01-21 16:26:17.737084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3665bce2f2a4'
down_revision = 'f05d62398913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.drop_column('company_details_locked')

    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_details_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.drop_column('company_details_locked')

    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_details_locked', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
