"""class

Revision ID: 36d897996b6c
Revises: cd2186d30271
Create Date: 2023-08-29 07:03:09.574633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d897996b6c'
down_revision = 'cd2186d30271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
