"""delete review

Revision ID: 49a8de6a9fd2
Revises: 2a3038a529ab
Create Date: 2025-01-12 22:17:21.735164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a8de6a9fd2'
down_revision = '2a3038a529ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('professionalism', sa.INTEGER(), nullable=True),
    sa.Column('quality', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.Column('communication', sa.INTEGER(), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
