"""hhh

Revision ID: 530b9570e274
Revises: ea440c5da7dc
Create Date: 2025-01-08 17:11:59.699311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530b9570e274'
down_revision = 'ea440c5da7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user2_id', sa.Integer(), nullable=True))
        batch_op.drop_column('chat_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('user2_id')

    # ### end Alembic commands ###
