"""Remove price_estimate field

Revision ID: 565d59ce3bb3
Revises: 4a8bf3ebf547
Create Date: 2024-11-27 16:09:35.149987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565d59ce3bb3'
down_revision = '4a8bf3ebf547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('price_per_hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_hour', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
