"""verified-statuses

Revision ID: 5a1a7271c203
Revises: 01b04e17e4f1
Create Date: 2025-01-12 12:59:18.713117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1a7271c203'
down_revision = '01b04e17e4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('insurance_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.drop_column('insurance_verified')
        batch_op.drop_column('id_verified')

    # ### end Alembic commands ###
