"""kkkl

Revision ID: 6844a73d16bf
Revises: c6f7dddd3b65
Create Date: 2025-01-06 00:09:46.391268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6844a73d16bf'
down_revision = 'c6f7dddd3b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('room')

    # ### end Alembic commands ###
