"""jhj

Revision ID: 784c529ca227
Revises: 3d114fb99caf
Create Date: 2025-01-06 19:02:32.560262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784c529ca227'
down_revision = '3d114fb99caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
