"""delete_user

Revision ID: 7e1348adf1fa
Revises: 31e6d2df4d92
Create Date: 2025-01-14 15:35:53.681075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1348adf1fa'
down_revision = '31e6d2df4d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soft_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('soft_deleted')

    # ### end Alembic commands ###
