"""timestamp

Revision ID: 830fe1dc0f5b
Revises: 0316aec7ed39
Create Date: 2025-04-07 23:04:00.069526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830fe1dc0f5b'
down_revision = '0316aec7ed39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
