"""Update Job model to reference User instead of BusinessProfile

Revision ID: 8a1eea3c8bb1
Revises: f5ee68fb629c
Create Date: 2024-11-25 21:10:30.855265
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1eea3c8bb1'
down_revision = 'f5ee68fb629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        # Specify the name for the foreign key constraint
        batch_op.create_foreign_key('fk_job_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        # Drop the foreign key constraint using the specified name
        batch_op.drop_constraint('fk_job_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
