"""revert

Revision ID: 94693f9c9a10
Revises: ba051f3aac76
Create Date: 2025-01-17 02:48:49.616097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94693f9c9a10'
down_revision = 'ba051f3aac76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
