"""Add location column back to Job model

Revision ID: a7dd77df3e81
Revises: 478bc0d74008
Create Date: 2024-11-25 17:35:19.929542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7dd77df3e81'
down_revision = '478bc0d74008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.alter_column('job_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('job_category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('location')

    # ### end Alembic commands ###
