"""kok

Revision ID: a8502724f28a
Revises: c3252d57392f
Create Date: 2024-01-23 14:15:21.894375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8502724f28a'
down_revision = 'c3252d57392f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('image_paths')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_paths', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
