"""opo

Revision ID: a893b2430b66
Revises: c9cf426b4717
Create Date: 2024-12-10 23:43:31.616604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a893b2430b66'
down_revision = 'c9cf426b4717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('balls', 'job_application', ['job_application_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('balls', type_='foreignkey')
        batch_op.drop_column('job_application_id')

    # ### end Alembic commands ###
