"""Make contact_number nullable

Revision ID: be6dfe9457af
Revises: 8a1eea3c8bb1
Create Date: 2024-11-28 02:44:03.495108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6dfe9457af'
down_revision = '8a1eea3c8bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.drop_column('price_per_hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_hour', sa.FLOAT(), nullable=False))
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
