"""lpl

Revision ID: c184170f946a
Revises: 0c3cf0c12ab5
Create Date: 2024-01-17 09:11:46.414800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c184170f946a'
down_revision = '0c3cf0c12ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('accepted_user_id')

    # ### end Alembic commands ###
