"""gearpostedits

Revision ID: c22ef89c74c6
Revises: 59c9fab16273
Create Date: 2025-03-13 23:29:16.564525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22ef89c74c6'
down_revision = '59c9fab16273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_day', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_per_week', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_per_half_day', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pickup_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivery_available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bond_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bond_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_post', schema=None) as batch_op:
        batch_op.drop_column('bond_amount')
        batch_op.drop_column('bond_required')
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('delivery_available')
        batch_op.drop_column('pickup_only')
        batch_op.drop_column('price_per_half_day')
        batch_op.drop_column('price_per_week')
        batch_op.drop_column('price_per_day')

    # ### end Alembic commands ###
