"""add city/suburb

Revision ID: cb932a4a10ab
Revises: 3665bce2f2a4
Create Date: 2025-03-06 20:09:23.055328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb932a4a10ab'
down_revision = '3665bce2f2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_suburb', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('city_suburb')

    # ### end Alembic commands ###
