"""idimage

Revision ID: d6ae25431695
Revises: f4ba12cdeb3a
Create Date: 2025-01-11 16:48:47.588142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ae25431695'
down_revision = 'f4ba12cdeb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_image', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labourer_profile', schema=None) as batch_op:
        batch_op.drop_column('id_image')

    # ### end Alembic commands ###
