"""sociallink

Revision ID: e642e4bd643f
Revises: 2b6360ec8108
Create Date: 2024-11-30 20:45:10.423827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e642e4bd643f'
down_revision = '2b6360ec8108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.drop_column('google')

    # ### end Alembic commands ###
