"""addvisible

Revision ID: eb95a2309d05
Revises: 19f8a3238290
Create Date: 2024-12-05 15:53:39.431129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb95a2309d05'
down_revision = '19f8a3238290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
