"""pop

Revision ID: ecfb8cef9635
Revises: cd9d88d951ff
Create Date: 2024-01-24 09:19:45.586755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfb8cef9635'
down_revision = 'cd9d88d951ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('nzbn', sa.String(length=100), nullable=True),
    sa.Column('director_first_name', sa.String(length=50), nullable=False),
    sa.Column('director_last_name', sa.String(length=50), nullable=False),
    sa.Column('physical_address', sa.String(length=100), nullable=False),
    sa.Column('unit_no', sa.String(length=10), nullable=True),
    sa.Column('trading_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_details')
    # ### end Alembic commands ###
