"""add lock details

Revision ID: f05d62398913
Revises: 7e911cf67597
Create Date: 2025-01-21 16:17:47.980991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05d62398913'
down_revision = '7e911cf67597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_details_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_details', schema=None) as batch_op:
        batch_op.drop_column('company_details_locked')

    # ### end Alembic commands ###
