"""added saved classes

Revision ID: f4ba12cdeb3a
Revises: e5a694336efb
Create Date: 2025-01-11 13:59:00.554176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ba12cdeb3a'
down_revision = 'e5a694336efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_by_users', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('saved_by_users')

    # ### end Alembic commands ###
