"""Simplify BusinessProfile to only have user_id

Revision ID: f5ee68fb629c
Revises: 2ea821b45ab0
Create Date: 2024-11-25 20:43:43.354379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ee68fb629c'
down_revision = '2ea821b45ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.drop_column('street')
        batch_op.drop_column('suburb')
        batch_op.drop_column('business_name')
        batch_op.drop_column('city')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('number')
        batch_op.drop_column('first_name')
        batch_op.drop_column('business_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('number', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('business_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('suburb', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
